// <auto-generated />
using System;
using BlazorPastaShop.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorPastaShop.Data.Migrations
{
    [DbContext(typeof(BlazorPastaShopDbContext))]
    [Migration("20251001102124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorPastaShop.Data.Models.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PastaId")
                        .HasColumnType("int");

                    b.Property<int>("PortieId")
                        .HasColumnType("int");

                    b.Property<int>("SausId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PastaId");

                    b.HasIndex("PortieId");

                    b.HasIndex("SausId");

                    b.ToTable("Bestellingen");
                });

            modelBuilder.Entity("BlazorPastaShop.Data.Models.Klant", b =>
                {
                    b.Property<int>("KlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlantId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeboorteDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlantId");

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("BlazorPastaShop.Data.Models.Pasta", b =>
                {
                    b.Property<int>("PastaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PastaId"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PastaId");

                    b.ToTable("Pasta");
                });

            modelBuilder.Entity("BlazorPastaShop.Data.Models.Portie", b =>
                {
                    b.Property<int>("PortieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortieId"));

                    b.Property<string>("Grootte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortieId");

                    b.ToTable("Porties");
                });

            modelBuilder.Entity("BlazorPastaShop.Data.Models.Saus", b =>
                {
                    b.Property<int>("SausId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SausId"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SausId");

                    b.ToTable("Sauzen");
                });

            modelBuilder.Entity("BlazorPastaShop.Data.Models.Bestelling", b =>
                {
                    b.HasOne("BlazorPastaShop.Data.Models.Pasta", "Pasta")
                        .WithMany("Bestellingen")
                        .HasForeignKey("PastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorPastaShop.Data.Models.Portie", "Portie")
                        .WithMany("Bestellingen")
                        .HasForeignKey("PortieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorPastaShop.Data.Models.Saus", "Saus")
                        .WithMany("Bestellingen")
                        .HasForeignKey("SausId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pasta");

                    b.Navigation("Portie");

                    b.Navigation("Saus");
                });

            modelBuilder.Entity("BlazorPastaShop.Data.Models.Pasta", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("BlazorPastaShop.Data.Models.Portie", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("BlazorPastaShop.Data.Models.Saus", b =>
                {
                    b.Navigation("Bestellingen");
                });
#pragma warning restore 612, 618
        }
    }
}
